In [ ]:
cd /kaggle/working/

In [ ]:
import shutil
shutil.rmtree("/kaggle/working/BaNLAD_SwinDocSegmenter")

In [ ]:
!git clone https://github.com/RadeenXALNW/BaNLAD_SwinDocSegmenter.git

In [1]:
cd /kaggle/working/BaNLAD_SwinDocSegmenter

/kaggle/working/BaNLAD_SwinDocSegmenter

In [ ]:

!pip install 'git+https://github.com/facebookresearch/detectron2.git'

In [ ]:
from detectron2 import _C

In [2]:
import detectron2.utils.comm as comm
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.config import get_cfg
from detectron2.data import MetadataCatalog, build_detection_train_loader
from detectron2.modeling import GeneralizedRCNNWithTTA
from detectron2.evaluation import (
    CityscapesInstanceEvaluator,
    CityscapesSemSegEvaluator,
    COCOEvaluator,
    COCOPanopticEvaluator,
    DatasetEvaluators,
    LVISEvaluator,
    SemSegEvaluator,
    verify_results,
)
from detectron2.projects.deeplab import add_deeplab_config, build_lr_scheduler
from detectron2.solver.build import maybe_add_gradient_clipping
from detectron2.utils.logger import setup_logger

from detectron2.data.datasets import register_coco_instances
from detectron2.data.datasets.coco import convert_to_coco_json
from detectron2.engine import (
    DefaultTrainer,
    default_argument_parser,
    default_setup,
    hooks,
    launch,
    create_ddp_model,
    AMPTrainer,
    SimpleTrainer
)

from IPython.display import FileLink
import sys
# torch
import torch

import gc

from detectron2.utils.memory import retry_if_cuda_oom
from detectron2.utils.logger import setup_logger
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.modeling import build_model
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
import detectron2.data.transforms as T
from detectron2.data import detection_utils as utils
from detectron2.data import DatasetCatalog, MetadataCatalog, build_detection_test_loader, build_detection_train_loader, DatasetMapper
from detectron2.utils.visualizer import Visualizer
from detectron2.structures import BoxMode
from detectron2.engine import DefaultPredictor, DefaultTrainer
from detectron2.config import get_cfg
from detectron2 import model_zoo

import pandas as pd
import numpy as np
from tqdm.notebook import tqdm  # progress bar
import matplotlib.pyplot as plt
import json
import cv2
import copy
from typing import Optional


from IPython.display import FileLink
import sys
# torch
import torch

import gc

import warnings
# Ignore "future" warnings and Data-Frame-Slicing warnings.
warnings.filterwarnings('ignore')

setup_logger()

In [ ]:
!pip install -r requirements.txt

In [ ]:
!cd maskdino/modeling/pixel_decoder/ops && sh make.sh

In [ ]:
# !pip install gdown 
# !gdown 17F-81EFkyKXhOIt7m65rYfaKeQTu7rL1
# !gdown 1180cKcF1gRwI6RMI926sRsoiugxWWQty
# !gdown 1vjwERzB-e7OL6cSg0gAYxRHOJR9j1PAg
!gdown 1LtlZSWUulPptyoklz8rsXwWa0FcVC8K8

In [ ]:
import os 
os.makedirs("output")

In [ ]:
!mv /kaggle/working/BaNLAD_SwinDocSegmenter/model_final.pth /kaggle/working/BaNLAD_SwinDocSegmenter/output

In [ ]:
!mv /kaggle/working/BaNLAD_SwinDocSegmenter/last_checkpoint /kaggle/working/BaNLAD_SwinDocSegmenter/output

In [3]:
from maskdino import (
    COCOInstanceNewBaselineDatasetMapper,
    COCOPanopticNewBaselineDatasetMapper,
    InstanceSegEvaluator,
    MaskFormerSemanticDatasetMapper,
    SemanticSegmentorWithTTA,
    add_maskformer2_config,
    DetrDatasetMapper,
)

In [ ]:
cfg = get_cfg()
# for poly lr schedule
add_deeplab_config(cfg)
add_maskformer2_config(cfg)
cfg.merge_from_file("/kaggle/working/BaNLAD_SwinDocSegmenter/maskdino_R50_bs16_50ep_3s.yaml")
print(cfg)

In [ ]:
from train_net import Trainer

In [4]:
### Data load
torch.cuda.empty_cache()
from pathlib import Path

TRAIN_IMG_DIR = Path("/kaggle/input/banlad2599-bangla-newspaper-layout-dataset/All_Crumpled_Images")

TRAIN_COCO_PATH=Path("/kaggle/working/BaNLAD_SwinDocSegmenter/updated_coco.json")

# Training output directory
OUTPUT_DIR = Path("output")
OUTPUT_MODEL = OUTPUT_DIR/"model_final.pth"

# Path to your pretrained model weights
PRETRAINED_PATH = Path("/kaggle/working/model_final.pth")

In [5]:
import json
### Coco Annotation
from pycocotools.coco import COCO

with TRAIN_COCO_PATH.open() as f:
    train_dict = json.load(f)

train_coco_labels=COCO(annotation_file=TRAIN_COCO_PATH)

print("#### LABELS AND METADATA LOADED ####")

loading annotations into memory...
Done (t=6.95s)
creating index...
index created!
#### LABELS AND METADATA LOADED ####

In [6]:
#Decisions

from datetime import datetime

# if False, model is set to `PRETRAINED_PATH` model
is_train = True

# if True, evaluate on validation dataset
is_evaluate = False

# if True, run inference on test dataset
is_inference = True

# if True and `is_train` == True, `PRETRAINED_PATH` model is trained further
is_resume_training = True

# Perform augmentation
is_augment = True

SEED = 1234

# Model path based on Decisions
MODEL_PATH = OUTPUT_MODEL if is_train else PRETRAINED_PATH

In [7]:
print("There are " + str(len(train_dict['categories'])) + " categories.\n")
# print("There are " + str(len(test_dict['images']) + len(train_dict['images'])) + " images in the dataset.")
print("There are " + str(len(train_dict['images'])) + " images in the train set.")
# print("There are " + str(len(test_dict['images'])) + " images in the test set.\n")
print("There are " + str(len(train_dict['annotations'])) + " annotations in the train set.\n")

print("We will focus on mainly categories, images and annotations.")

There are 6 categories.

There are 2726 images in the train set.
There are 641353 annotations in the train set.

We will focus on mainly categories, images and annotations.

In [8]:
def organize_coco_data(data_dict: dict) -> tuple[list[str], list[dict], list[dict]]:
    thing_classes: list[str] = []

    # Map Category Names to IDs
    for cat in data_dict['categories']:
        thing_classes.append(cat['name'])

    # Images
    images_metadata: list[dict] = data_dict['images']

    # Convert COCO annotations to detectron2 annotations format
    data_annotations = []
    for ann in data_dict['annotations']:
        # coco format -> detectron2 format
        annot_obj = {
            # Annotation ID
            "id": ann['id'],

            # Segmentation Polygon (x, y) coordinnates
            "gt_masks": ann['segmentation'],

            # Image ID for this annotation (Which image does this annotation belong to?)
            "image_id": ann['image_id'],

            # Category Label (0: paragraph, 1: text box, 2: image, 3: table)
            "category_id": ann['category_id'],

            "x_min": ann['bbox'][0],  # left
            "y_min": ann['bbox'][1],  # top
            "x_max": ann['bbox'][0] + ann['bbox'][2],  # left+width
            "y_max": ann['bbox'][1] + ann['bbox'][3]  # top+height
        }
        data_annotations.append(annot_obj)

    return thing_classes, images_metadata, data_annotations

In [9]:
thing_classes, images_metadata, data_annotations = organize_coco_data(train_dict)

# thing_classes_test, images_metadata_test, _ = organize_coco_data(test_dict)

print(thing_classes)
# thing_classes = [cls for cls in thing_classes if cls != 'newspaper']

print(len(thing_classes))

['news', 'image', 'news', 'paragraph', 'table', 'text-box']
6

In [10]:
train_metadata = pd.DataFrame(images_metadata)
train_metadata = train_metadata[['id', 'file_name', 'width', 'height']]
train_metadata = train_metadata.rename(columns={"id": "image_id"})
print("train_metadata size=", len(train_metadata))
train_metadata.head(5)

train_metadata size= 2726

   image_id                                          file_name  width  height
0         0  image_249_png.rf.24e6802439adcea910092682ce070...   2592    4608
1         1  image_232_png.rf.206a044d134b5893141ae01bf4a42...   2592    4608
2         2  image_202_png.rf.14185520c66db852b1c1a0f12b9aa...   3000    4000
3         3  image_198_png.rf.10d4c751aa2909875cf306d0eb514...   2592    4608
4         4  image_165_png.rf.054e36e83984ebbe210819bbbed0a...   3024    4032

In [11]:
train_annot_df = pd.DataFrame(data_annotations)
print("train_annot_df size=", len(train_annot_df))
train_annot_df.head(5)

train_annot_df size= 641353

,id,gt_masks,image_id,category_id,x_min,y_min,x_max,y_max
0,0,"[[1377.5, 341.255, 1612.5, 341.255, 1612.5, 44...",0,5,1378,341,1613.000,447.25
1,1,"[[1616, 490, 529, 510, 525, 904, 528, 1366, 51...",0,2,515,490,1680.000,2206.00
2,2,"[[2107.5, 427.5, 1891.25, 431.25, 1630, 457.5,...",0,3,1618,324,2340.525,457.75
3,3,"[[1351.275, 323.75, 1362.525, 457.5, 1632.525,...",0,2,1351,309,2349.750,472.75
4,4,"[[1618.775, 487.5, 1782.525, 467.5, 1970.025, ...",0,5,1619,468,1981.500,596.75

In [12]:
#Formatting Data for detectron2
def convert_coco_to_detectron2_format(
    imgdir: Path,
    metadata_df: pd.DataFrame,
    annot_df: Optional[pd.DataFrame] = None,
    target_indices: Optional[np.ndarray] = None,
):

    dataset_dicts = []
    for _, train_meta_row in tqdm(metadata_df.iterrows(), total=len(metadata_df)):
        # Iterate over each image
        image_id, filename, width, height = train_meta_row.values

        annotations = []
        
        # If train/validation data, then there will be annotations
        if annot_df is not None:
            for _, ann in annot_df.query("image_id == @image_id").iterrows():
                # Get annotations of current iteration's image
                class_id = ann["category_id"]
                gt_masks = ann["gt_masks"]
                bbox_resized = [
                    float(ann["x_min"]),
                    float(ann["y_min"]),
                    float(ann["x_max"]),
                    float(ann["y_max"]),
                ]

                annotation = {
                    "bbox": bbox_resized,
                    "bbox_mode": BoxMode.XYXY_ABS,
                    "segmentation": gt_masks,
                    "category_id": class_id,
                }

                annotations.append(annotation)
        # coco format -> detectron2 format dict
        record = {
            "file_name": str(imgdir/filename),
            "image_id": image_id,
            "width": width,
            "height": height,
            "annotations": annotations
        }

        dataset_dicts.append(record)

    if target_indices is not None:
        dataset_dicts = [dataset_dicts[i] for i in target_indices]

    return dataset_dicts

In [13]:
DatasetCatalog.clear()

In [14]:
TRAIN_SPLIT = 0.90
n_dataset = len(train_metadata)
n_train = int(n_dataset * TRAIN_SPLIT)
print("n_dataset", n_dataset, "n_train", n_train, "n_val", n_dataset-n_train)

np.random.seed(SEED)

inds = np.random.permutation(n_dataset)
train_inds, valid_inds = inds[:n_train], inds[n_train:]

n_dataset 2726 n_train 2453 n_val 273

In [15]:
#Registering and Loading Data for detectron2
DATA_REGISTER_TRAINING = "pub_train"
DATA_REGISTER_VALID    = "pub_val"
DATA_REGISTER_TEST     = "badlad_test"

In [16]:
# Register Training data
if is_train:
    DatasetCatalog.register(
        DATA_REGISTER_TRAINING,
        lambda: convert_coco_to_detectron2_format(
            TRAIN_IMG_DIR,
            train_metadata,
            train_annot_df,
            target_indices=train_inds,
        ),
    )

    # Set Training data categories
    MetadataCatalog.get(DATA_REGISTER_TRAINING).set(thing_classes=thing_classes)

    dataset_dicts_train = DatasetCatalog.get(DATA_REGISTER_TRAINING)
    metadata_dicts_train = MetadataCatalog.get(DATA_REGISTER_TRAINING)

    print("dicts training size=", len(dataset_dicts_train))
    print("################")

  0%|          | 0/2726 [00:00<?, ?it/s]

dicts training size= 2453
################

In [ ]:
def custom_mapper(dataset_dict):
    dataset_dict = copy.deepcopy(dataset_dict)
    image = utils.read_image(dataset_dict["file_name"], format="BGR")

    transform_list = [#T.RandomBrightness(0.8, 1.2),
#                       T.RandomFlip(prob=0.5, horizontal=False, vertical=True)
                        T.Resize((512,512))
                      #T.RandomFlip(prob=0.5, horizontal=True, vertical=False)
                      ]
    image, transforms = T.apply_transform_gens(transform_list, image)

    dataset_dict["image"] = torch.as_tensor(
        image.transpose(2, 0, 1).astype("float32"))

    annos = [
        utils.transform_instance_annotations(obj, transforms, image.shape[:2])
        for obj in dataset_dict.pop("annotations")
        if obj.get("iscrowd", 0) == 0
    ]
    instances = utils.annotations_to_instances(annos, image.shape[:2])

    dataset_dict["instances"] = utils.filter_empty_instances(instances)

In [ ]:
from train_net import Trainer
class AugTrainer1(Trainer):
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=custom_mapper)

In [ ]:
!gdown 1DCxG2MCza_z-yB3bLcaVvVR4Jik00Ecq

In [ ]:
import warnings

# Suppress all warnings
warnings.filterwarnings("ignore")

In [ ]:
from train_net import Trainer
if is_train:  
    cfg = get_cfg()
    # for poly lr schedule
    add_deeplab_config(cfg)
    add_maskformer2_config(cfg)
    cfg.DATASETS.TRAIN = (DATA_REGISTER_TRAINING,)
    cfg.merge_from_file("maskdino_R50_bs16_50ep_3s.yaml")
    cfg.MODEL.DEVICE = "cuda" 
    cfg.SOLVER.AMP.ENABLED = True
    cfg.DATALOADER.NUM_WORKERS =2
    
    cfg.MODEL.WEIGHTS = "/kaggle/working/BaNLAD_SwinDocSegmenter/output/model_final.pth"
    # cfg.INPUT.CROP.ENABLED=True
    cfg.SOLVER.AMP.ENABLED = True
    cfg.SOLVER.IMS_PER_BATCH = 1
    cfg.SOLVER.BASE_LR = 0.001
    cfg.SOLVER.STEPS = (500, 1000)
    cfg.SOLVER.WARMUP_ITERS = 5
    cfg.INPUT.DATASET_MAPPER_NAME = "coco_instance_lsj"
    cfg.INPUT.IMAGE_SIZE=512
    
    # Maximum number of iterations
    cfg.SOLVER.MAX_ITER = 60000
    cfg.TEST.EVAL_PERIOD=80000
    cfg.SOLVER.CHECKPOINT_PERIOD = 5000

    # cfg.SOLVER.STEPS = (500, 1000) # must be less than MAX_ITER

    cfg.SOLVER.GAMMA = 0.09
    # Small value == Frequent save need a lot of storage.
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 8
    cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = 6
    cfg.OUTPUT_DIR = str(OUTPUT_DIR)
    trainer = Trainer(cfg)
    print(trainer)
    trainer.resume_or_load(resume=is_resume_training)

    trainer.train()

criterion.weight_dict  {'loss_ce': 4.0, 'loss_mask': 5.0, 'loss_dice': 5.0, 'loss_bbox': 5.0, 'loss_giou': 2.0, 'loss_ce_interm': 4.0, 'loss_mask_interm': 5.0, 'loss_dice_interm': 5.0, 'loss_bbox_interm': 5.0, 'loss_giou_interm': 2.0, 'loss_ce_dn': 4.0, 'loss_mask_dn': 5.0, 'loss_dice_dn': 5.0, 'loss_bbox_dn': 5.0, 'loss_giou_dn': 2.0, 'loss_ce_interm_dn': 4.0, 'loss_mask_interm_dn': 5.0, 'loss_dice_interm_dn': 5.0, 'loss_bbox_interm_dn': 5.0, 'loss_giou_interm_dn': 2.0, 'loss_ce_0': 4.0, 'loss_mask_0': 5.0, 'loss_dice_0': 5.0, 'loss_bbox_0': 5.0, 'loss_giou_0': 2.0, 'loss_ce_interm_0': 4.0, 'loss_mask_interm_0': 5.0, 'loss_dice_interm_0': 5.0, 'loss_bbox_interm_0': 5.0, 'loss_giou_interm_0': 2.0, 'loss_ce_dn_0': 4.0, 'loss_mask_dn_0': 5.0, 'loss_dice_dn_0': 5.0, 'loss_bbox_dn_0': 5.0, 'loss_giou_dn_0': 2.0, 'loss_ce_interm_dn_0': 4.0, 'loss_mask_interm_dn_0': 5.0, 'loss_dice_interm_dn_0': 5.0, 'loss_bbox_interm_dn_0': 5.0, 'loss_giou_interm_dn_0': 2.0, 'loss_ce_1': 4.0, 'loss_mask_1': 5.0, 'loss_dice_1': 5.0, 'loss_bbox_1': 5.0, 'loss_giou_1': 2.0, 'loss_ce_interm_1': 4.0, 'loss_mask_interm_1': 5.0, 'loss_dice_interm_1': 5.0, 'loss_bbox_interm_1': 5.0, 'loss_giou_interm_1': 2.0, 'loss_ce_dn_1': 4.0, 'loss_mask_dn_1': 5.0, 'loss_dice_dn_1': 5.0, 'loss_bbox_dn_1': 5.0, 'loss_giou_dn_1': 2.0, 'loss_ce_interm_dn_1': 4.0, 'loss_mask_interm_dn_1': 5.0, 'loss_dice_interm_dn_1': 5.0, 'loss_bbox_interm_dn_1': 5.0, 'loss_giou_interm_dn_1': 2.0, 'loss_ce_2': 4.0, 'loss_mask_2': 5.0, 'loss_dice_2': 5.0, 'loss_bbox_2': 5.0, 'loss_giou_2': 2.0, 'loss_ce_interm_2': 4.0, 'loss_mask_interm_2': 5.0, 'loss_dice_interm_2': 5.0, 'loss_bbox_interm_2': 5.0, 'loss_giou_interm_2': 2.0, 'loss_ce_dn_2': 4.0, 'loss_mask_dn_2': 5.0, 'loss_dice_dn_2': 5.0, 'loss_bbox_dn_2': 5.0, 'loss_giou_dn_2': 2.0, 'loss_ce_interm_dn_2': 4.0, 'loss_mask_interm_dn_2': 5.0, 'loss_dice_interm_dn_2': 5.0, 'loss_bbox_interm_dn_2': 5.0, 'loss_giou_interm_dn_2': 2.0, 'loss_ce_3': 4.0, 'loss_mask_3': 5.0, 'loss_dice_3': 5.0, 'loss_bbox_3': 5.0, 'loss_giou_3': 2.0, 'loss_ce_interm_3': 4.0, 'loss_mask_interm_3': 5.0, 'loss_dice_interm_3': 5.0, 'loss_bbox_interm_3': 5.0, 'loss_giou_interm_3': 2.0, 'loss_ce_dn_3': 4.0, 'loss_mask_dn_3': 5.0, 'loss_dice_dn_3': 5.0, 'loss_bbox_dn_3': 5.0, 'loss_giou_dn_3': 2.0, 'loss_ce_interm_dn_3': 4.0, 'loss_mask_interm_dn_3': 5.0, 'loss_dice_interm_dn_3': 5.0, 'loss_bbox_interm_dn_3': 5.0, 'loss_giou_interm_dn_3': 2.0, 'loss_ce_4': 4.0, 'loss_mask_4': 5.0, 'loss_dice_4': 5.0, 'loss_bbox_4': 5.0, 'loss_giou_4': 2.0, 'loss_ce_interm_4': 4.0, 'loss_mask_interm_4': 5.0, 'loss_dice_interm_4': 5.0, 'loss_bbox_interm_4': 5.0, 'loss_giou_interm_4': 2.0, 'loss_ce_dn_4': 4.0, 'loss_mask_dn_4': 5.0, 'loss_dice_dn_4': 5.0, 'loss_bbox_dn_4': 5.0, 'loss_giou_dn_4': 2.0, 'loss_ce_interm_dn_4': 4.0, 'loss_mask_interm_dn_4': 5.0, 'loss_dice_interm_dn_4': 5.0, 'loss_bbox_interm_dn_4': 5.0, 'loss_giou_interm_dn_4': 2.0, 'loss_ce_5': 4.0, 'loss_mask_5': 5.0, 'loss_dice_5': 5.0, 'loss_bbox_5': 5.0, 'loss_giou_5': 2.0, 'loss_ce_interm_5': 4.0, 'loss_mask_interm_5': 5.0, 'loss_dice_interm_5': 5.0, 'loss_bbox_interm_5': 5.0, 'loss_giou_interm_5': 2.0, 'loss_ce_dn_5': 4.0, 'loss_mask_dn_5': 5.0, 'loss_dice_dn_5': 5.0, 'loss_bbox_dn_5': 5.0, 'loss_giou_dn_5': 2.0, 'loss_ce_interm_dn_5': 4.0, 'loss_mask_interm_dn_5': 5.0, 'loss_dice_interm_dn_5': 5.0, 'loss_bbox_interm_dn_5': 5.0, 'loss_giou_interm_dn_5': 2.0, 'loss_ce_6': 4.0, 'loss_mask_6': 5.0, 'loss_dice_6': 5.0, 'loss_bbox_6': 5.0, 'loss_giou_6': 2.0, 'loss_ce_interm_6': 4.0, 'loss_mask_interm_6': 5.0, 'loss_dice_interm_6': 5.0, 'loss_bbox_interm_6': 5.0, 'loss_giou_interm_6': 2.0, 'loss_ce_dn_6': 4.0, 'loss_mask_dn_6': 5.0, 'loss_dice_dn_6': 5.0, 'loss_bbox_dn_6': 5.0, 'loss_giou_dn_6': 2.0, 'loss_ce_interm_dn_6': 4.0, 'loss_mask_interm_dn_6': 5.0, 'loss_dice_interm_dn_6': 5.0, 'loss_bbox_interm_dn_6': 5.0, 'loss_giou_interm_dn_6': 2.0, 'loss_ce_7': 4.0, 'loss_mask_7': 5.0, 'loss_dice_7': 5.0, 'loss_bbox_7': 5.0, 'loss_giou_7': 2.0, 'loss_ce_interm_7': 4.0, 'loss_mask_interm_7': 5.0, 'loss_dice_interm_7': 5.0, 'loss_bbox_interm_7': 5.0, 'loss_giou_interm_7': 2.0, 'loss_ce_dn_7': 4.0, 'loss_mask_dn_7': 5.0, 'loss_dice_dn_7': 5.0, 'loss_bbox_dn_7': 5.0, 'loss_giou_dn_7': 2.0, 'loss_ce_interm_dn_7': 4.0, 'loss_mask_interm_dn_7': 5.0, 'loss_dice_interm_dn_7': 5.0, 'loss_bbox_interm_dn_7': 5.0, 'loss_giou_interm_dn_7': 2.0, 'loss_ce_8': 4.0, 'loss_mask_8': 5.0, 'loss_dice_8': 5.0, 'loss_bbox_8': 5.0, 'loss_giou_8': 2.0, 'loss_ce_interm_8': 4.0, 'loss_mask_interm_8': 5.0, 'loss_dice_interm_8': 5.0, 'loss_bbox_interm_8': 5.0, 'loss_giou_interm_8': 2.0, 'loss_ce_dn_8': 4.0, 'loss_mask_dn_8': 5.0, 'loss_dice_dn_8': 5.0, 'loss_bbox_dn_8': 5.0, 'loss_giou_dn_8': 2.0, 'loss_ce_interm_dn_8': 4.0, 'loss_mask_interm_dn_8': 5.0, 'loss_dice_interm_dn_8': 5.0, 'loss_bbox_interm_dn_8': 5.0, 'loss_giou_interm_dn_8': 2.0}
[08/19 22:11:54 d2.engine.defaults]: Model:
MaskDINO(
  (backbone): D2SwinTransformer(
    (patch_embed): PatchEmbed(
      (proj): Conv2d(3, 192, kernel_size=(4, 4), stride=(4, 4))
      (norm): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
    )
    (pos_drop): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0): BasicLayer(
        (blocks): ModuleList(
          (0): SwinTransformerBlock(
            (norm1): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=192, out_features=576, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=192, out_features=192, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): Identity()
            (norm2): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=192, out_features=768, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=768, out_features=192, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (1): SwinTransformerBlock(
            (norm1): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=192, out_features=576, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=192, out_features=192, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.013)
            (norm2): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=192, out_features=768, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=768, out_features=192, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
        )
        (downsample): PatchMerging(
          (reduction): Linear(in_features=768, out_features=384, bias=False)
          (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
      (1): BasicLayer(
        (blocks): ModuleList(
          (0): SwinTransformerBlock(
            (norm1): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=384, out_features=1152, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=384, out_features=384, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.026)
            (norm2): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=384, out_features=1536, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=1536, out_features=384, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (1): SwinTransformerBlock(
            (norm1): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=384, out_features=1152, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=384, out_features=384, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.039)
            (norm2): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=384, out_features=1536, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=1536, out_features=384, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
        )
        (downsample): PatchMerging(
          (reduction): Linear(in_features=1536, out_features=768, bias=False)
          (norm): LayerNorm((1536,), eps=1e-05, elementwise_affine=True)
        )
      )
      (2): BasicLayer(
        (blocks): ModuleList(
          (0): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.052)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (1): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.065)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (2): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.078)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (3): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.091)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (4): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.104)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (5): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.117)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (6): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.130)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (7): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.143)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (8): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.157)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (9): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.170)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (10): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.183)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)
              (drop): Dropout(p=0.0, inplace=False)
            )
          )
          (11): SwinTransformerBlock(
            (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (attn): WindowAttention(
              (qkv): Linear(in_features=768, out_features=2304, bias=True)
              (attn_drop): Dropout(p=0.0, inplace=False)
              (proj): Linear(in_features=768, out_features=768, bias=True)
              (proj_drop): Dropout(p=0.0, inplace=False)
              (softmax): Softmax(dim=-1)
            )
            (drop_path): DropPath(drop_prob=0.196)
            (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (mlp): Mlp(
              (fc1): Linear(in_features=768, out_features=3072, bias=True)
              (act): GELU(approximate='none')
              (fc2): Linear(in_features=3072, out_features=768, bias=True)

  0%|          | 0/2726 [00:00<?, ?it/s]

[08/19 22:12:56 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|    news    | 0            |   image    | 22992        |    news    | 44399        |
| paragraph  | 177332       |   table    | 1822         |  text-box  | 324198       |
|            |              |            |              |            |              |
|   total    | 570743       |            |              |            |              |
[08/19 22:12:56 d2.data.build]: Using training sampler TrainingSampler
[08/19 22:12:56 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[08/19 22:12:56 d2.data.common]: Serializing 2453 elements to byte tensors and concatenating them all ...
[08/19 22:12:57 d2.data.common]: Serialized dataset takes 87.84 MiB
[08/19 22:12:57 d2.data.build]: Making batched data loader with batch_size=1
<train_net.Trainer object at 0x7c7b9a4beef0>
[08/19 22:12:57 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from output/model_final.pth ...
[08/19 22:12:59 d2.engine.hooks]: Loading scheduler from state_dict ...
[08/19 22:12:59 d2.engine.train_loop]: Starting training from iteration 30000
[08/19 22:13:28 d2.utils.events]:  eta: 9:30:58  iter: 30019  total_loss: 80.54  loss_ce: 0.6504  loss_mask: 0.1871  loss_dice: 2.556  loss_bbox: 0.872  loss_giou: 2.583  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.8286  loss_mask_0: 0.1987  loss_dice_0: 2.802  loss_bbox_0: 1.069  loss_giou_0: 2.546  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.7522  loss_mask_1: 0.1988  loss_dice_1: 2.609  loss_bbox_1: 0.9806  loss_giou_1: 2.59  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.7644  loss_mask_2: 0.1999  loss_dice_2: 2.66  loss_bbox_2: 0.9512  loss_giou_2: 2.567  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.7161  loss_mask_3: 0.1948  loss_dice_3: 2.629  loss_bbox_3: 0.9373  loss_giou_3: 2.573  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.6701  loss_mask_4: 0.1837  loss_dice_4: 2.659  loss_bbox_4: 0.901  loss_giou_4: 2.569  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6915  loss_mask_5: 0.1984  loss_dice_5: 2.633  loss_bbox_5: 0.8864  loss_giou_5: 2.557  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6492  loss_mask_6: 0.175  loss_dice_6: 2.588  loss_bbox_6: 0.8812  loss_giou_6: 2.573  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6361  loss_mask_7: 0.1694  loss_dice_7: 2.584  loss_bbox_7: 0.878  loss_giou_7: 2.577  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.6306  loss_mask_8: 0.183  loss_dice_8: 2.563  loss_bbox_8: 0.8887  loss_giou_8: 2.584  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.8999  loss_mask_interm: 0.1803  loss_dice_interm: 2.911  loss_bbox_interm: 0.7195  loss_giou_interm: 1.959    time: 1.1915  last_time: 1.0818  data_time: 0.0562  last_data_time: 0.0096   lr: 8.1e-06  max_mem: 9413M

2024-08-19 22:13:28.587269: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-19 22:13:28.587328: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-19 22:13:28.588935: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

[08/19 22:13:56 d2.utils.events]:  eta: 9:25:26  iter: 30039  total_loss: 90.65  loss_ce: 0.663  loss_mask: 0.3043  loss_dice: 3.054  loss_bbox: 1.083  loss_giou: 2.242  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.9738  loss_mask_0: 0.3155  loss_dice_0: 3.333  loss_bbox_0: 1.254  loss_giou_0: 2.147  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.8268  loss_mask_1: 0.3441  loss_dice_1: 3.125  loss_bbox_1: 1.189  loss_giou_1: 2.195  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.7786  loss_mask_2: 0.3403  loss_dice_2: 3.181  loss_bbox_2: 1.168  loss_giou_2: 2.223  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.7297  loss_mask_3: 0.3586  loss_dice_3: 3.175  loss_bbox_3: 1.151  loss_giou_3: 2.236  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.7015  loss_mask_4: 0.3222  loss_dice_4: 3.19  loss_bbox_4: 1.176  loss_giou_4: 2.242  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.7045  loss_mask_5: 0.3274  loss_dice_5: 3.179  loss_bbox_5: 1.153  loss_giou_5: 2.241  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6957  loss_mask_6: 0.3031  loss_dice_6: 3.113  loss_bbox_6: 1.122  loss_giou_6: 2.246  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6656  loss_mask_7: 0.3143  loss_dice_7: 3.096  loss_bbox_7: 1.1  loss_giou_7: 2.242  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.6671  loss_mask_8: 0.3125  loss_dice_8: 3.087  loss_bbox_8: 1.092  loss_giou_8: 2.244  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.8797  loss_mask_interm: 0.2777  loss_dice_interm: 3.225  loss_bbox_interm: 0.8605  loss_giou_interm: 2.014    time: 1.1760  last_time: 1.0282  data_time: 0.0115  last_data_time: 0.0061   lr: 8.1e-06  max_mem: 9490M
[08/19 22:14:18 d2.utils.events]:  eta: 9:18:48  iter: 30059  total_loss: 84.49  loss_ce: 0.7198  loss_mask: 0.3386  loss_dice: 2.808  loss_bbox: 0.7716  loss_giou: 2.188  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.9117  loss_mask_0: 0.3482  loss_dice_0: 3.104  loss_bbox_0: 1.001  loss_giou_0: 2.096  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.9437  loss_mask_1: 0.338  loss_dice_1: 3.015  loss_bbox_1: 0.8701  loss_giou_1: 2.172  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.8314  loss_mask_2: 0.3395  loss_dice_2: 2.924  loss_bbox_2: 0.8193  loss_giou_2: 2.176  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.7368  loss_mask_3: 0.3426  loss_dice_3: 2.862  loss_bbox_3: 0.7783  loss_giou_3: 2.194  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.7258  loss_mask_4: 0.3489  loss_dice_4: 2.895  loss_bbox_4: 0.7732  loss_giou_4: 2.19  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6893  loss_mask_5: 0.3395  loss_dice_5: 2.815  loss_bbox_5: 0.7967  loss_giou_5: 2.213  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.7196  loss_mask_6: 0.331  loss_dice_6: 2.82  loss_bbox_6: 0.7715  loss_giou_6: 2.187  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.7252  loss_mask_7: 0.3324  loss_dice_7: 2.842  loss_bbox_7: 0.7672  loss_giou_7: 2.186  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.7154  loss_mask_8: 0.3417  loss_dice_8: 2.789  loss_bbox_8: 0.7684  loss_giou_8: 2.191  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.8927  loss_mask_interm: 0.3422  loss_dice_interm: 2.875  loss_bbox_interm: 0.6679  loss_giou_interm: 1.861    time: 1.1609  last_time: 1.0612  data_time: 0.0105  last_data_time: 0.0155   lr: 8.1e-06  max_mem: 9490M
[08/19 22:14:43 d2.utils.events]:  eta: 9:25:32  iter: 30079  total_loss: 93.25  loss_ce: 0.6667  loss_mask: 0.4146  loss_dice: 2.835  loss_bbox: 0.9678  loss_giou: 2.368  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.834  loss_mask_0: 0.4715  loss_dice_0: 3.135  loss_bbox_0: 1.118  loss_giou_0: 2.229  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.8123  loss_mask_1: 0.4651  loss_dice_1: 3.036  loss_bbox_1: 1.029  loss_giou_1: 2.3  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.7416  loss_mask_2: 0.4614  loss_dice_2: 3.042  loss_bbox_2: 1.014  loss_giou_2: 2.318  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.7481  loss_mask_3: 0.4568  loss_dice_3: 2.958  loss_bbox_3: 1.007  loss_giou_3: 2.357  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.717  loss_mask_4: 0.4235  loss_dice_4: 2.935  loss_bbox_4: 0.988  loss_giou_4: 2.373  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6778  loss_mask_5: 0.4256  loss_dice_5: 2.924  loss_bbox_5: 1.001  loss_giou_5: 2.361  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6768  loss_mask_6: 0.4155  loss_dice_6: 2.887  loss_bbox_6: 0.9774  loss_giou_6: 2.365  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6942  loss_mask_7: 0.4088  loss_dice_7: 2.827  loss_bbox_7: 0.9715  loss_giou_7: 2.362  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.6892  loss_mask_8: 0.4166  loss_dice_8: 2.807  loss_bbox_8: 0.961  loss_giou_8: 2.357  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.8272  loss_mask_interm: 0.4666  loss_dice_interm: 2.961  loss_bbox_interm: 0.7598  loss_giou_interm: 2.083    time: 1.1722  last_time: 1.0380  data_time: 0.0130  last_data_time: 0.0079   lr: 8.1e-06  max_mem: 9691M
[08/19 22:15:07 d2.utils.events]:  eta: 9:26:05  iter: 30099  total_loss: 90.62  loss_ce: 0.5055  loss_mask: 0.2906  loss_dice: 3.085  loss_bbox: 0.9217  loss_giou: 2.256  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.8127  loss_mask_0: 0.3305  loss_dice_0: 3.397  loss_bbox_0: 1.187  loss_giou_0: 2.266  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.7514  loss_mask_1: 0.3399  loss_dice_1: 3.246  loss_bbox_1: 1.029  loss_giou_1: 2.258  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.6496  loss_mask_2: 0.3236  loss_dice_2: 3.268  loss_bbox_2: 0.9808  loss_giou_2: 2.267  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.583  loss_mask_3: 0.3315  loss_dice_3: 3.16  loss_bbox_3: 0.9488  loss_giou_3: 2.297  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.5182  loss_mask_4: 0.3194  loss_dice_4: 3.195  loss_bbox_4: 0.957  loss_giou_4: 2.259  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.495  loss_mask_5: 0.308  loss_dice_5: 3.155  loss_bbox_5: 0.9567  loss_giou_5: 2.266  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.5151  loss_mask_6: 0.2998  loss_dice_6: 3.067  loss_bbox_6: 0.9382  loss_giou_6: 2.264  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.5093  loss_mask_7: 0.2998  loss_dice_7: 3.117  loss_bbox_7: 0.9252  loss_giou_7: 2.26  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.4962  loss_mask_8: 0.2996  loss_dice_8: 3.136  loss_bbox_8: 0.9282  loss_giou_8: 2.254  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.8184  loss_mask_interm: 0.3191  loss_dice_interm: 3.21  loss_bbox_interm: 0.8552  loss_giou_interm: 1.98    time: 1.1820  last_time: 1.1075  data_time: 0.0141  last_data_time: 0.0105   lr: 8.1e-06  max_mem: 10363M
[08/19 22:15:30 d2.utils.events]:  eta: 9:19:52  iter: 30119  total_loss: 83.37  loss_ce: 0.6567  loss_mask: 0.3148  loss_dice: 2.789  loss_bbox: 0.8124  loss_giou: 2.12  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 1.051  loss_mask_0: 0.3533  loss_dice_0: 3.017  loss_bbox_0: 1.096  loss_giou_0: 2.092  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.8903  loss_mask_1: 0.3544  loss_dice_1: 2.951  loss_bbox_1: 0.9575  loss_giou_1: 2.116  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.7554  loss_mask_2: 0.3711  loss_dice_2: 2.884  loss_bbox_2: 0.8957  loss_giou_2: 2.129  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.7412  loss_mask_3: 0.3198  loss_dice_3: 2.82  loss_bbox_3: 0.8502  loss_giou_3: 2.134  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.6891  loss_mask_4: 0.3368  loss_dice_4: 2.841  loss_bbox_4: 0.8492  loss_giou_4: 2.127  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6801  loss_mask_5: 0.3325  loss_dice_5: 2.805  loss_bbox_5: 0.8349  loss_giou_5: 2.136  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6393  loss_mask_6: 0.3329  loss_dice_6: 2.804  loss_bbox_6: 0.8261  loss_giou_6: 2.141  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6608  loss_mask_7: 0.3229  loss_dice_7: 2.852  loss_bbox_7: 0.8096  loss_giou_7: 2.114  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.6689  loss_mask_8: 0.3302  loss_dice_8: 2.804  loss_bbox_8: 0.8115  loss_giou_8: 2.128  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.9734  loss_mask_interm: 0.281  loss_dice_interm: 3.003  loss_bbox_interm: 0.5646  loss_giou_interm: 1.811    time: 1.1731  last_time: 1.1016  data_time: 0.0107  last_data_time: 0.0108   lr: 8.1e-06  max_mem: 10363M
[08/19 22:15:54 d2.utils.events]:  eta: 9:21:10  iter: 30139  total_loss: 75.52  loss_ce: 0.5927  loss_mask: 0.2201  loss_dice: 2.849  loss_bbox: 0.8207  loss_giou: 2.189  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.855  loss_mask_0: 0.2278  loss_dice_0: 3.145  loss_bbox_0: 1.043  loss_giou_0: 2.122  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.7543  loss_mask_1: 0.2103  loss_dice_1: 2.979  loss_bbox_1: 0.8863  loss_giou_1: 2.141  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.671  loss_mask_2: 0.2167  loss_dice_2: 3.035  loss_bbox_2: 0.8827  loss_giou_2: 2.149  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.6417  loss_mask_3: 0.2095  loss_dice_3: 2.988  loss_bbox_3: 0.8583  loss_giou_3: 2.17  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.6157  loss_mask_4: 0.2103  loss_dice_4: 2.902  loss_bbox_4: 0.8337  loss_giou_4: 2.192  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6162  loss_mask_5: 0.2107  loss_dice_5: 2.875  loss_bbox_5: 0.8361  loss_giou_5: 2.184  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6185  loss_mask_6: 0.22  loss_dice_6: 2.861  loss_bbox_6: 0.8259  loss_giou_6: 2.185  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6105  loss_mask_7: 0.2164  loss_dice_7: 2.862  loss_bbox_7: 0.8171  loss_giou_7: 2.17  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.596  loss_mask_8: 0.2228  loss_dice_8: 2.854  loss_bbox_8: 0.8225  loss_giou_8: 2.2  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.7825  loss_mask_interm: 0.1756  loss_dice_interm: 3.059  loss_bbox_interm: 0.6739  loss_giou_interm: 1.772    time: 1.1788  last_time: 1.4754  data_time: 0.0133  last_data_time: 0.0216   lr: 8.1e-06  max_mem: 10363M
[08/19 22:16:19 d2.utils.events]:  eta: 9:24:01  iter: 30159  total_loss: 75.69  loss_ce: 0.6055  loss_mask: 0.2149  loss_dice: 2.624  loss_bbox: 0.9011  loss_giou: 1.95  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.7557  loss_mask_0: 0.2155  loss_dice_0: 3.031  loss_bbox_0: 1.074  loss_giou_0: 1.869  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.7302  loss_mask_1: 0.2369  loss_dice_1: 2.761  loss_bbox_1: 0.9641  loss_giou_1: 1.862  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.7017  loss_mask_2: 0.2427  loss_dice_2: 2.745  loss_bbox_2: 0.932  loss_giou_2: 1.902  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.6536  loss_mask_3: 0.2164  loss_dice_3: 2.737  loss_bbox_3: 0.9287  loss_giou_3: 1.95  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.6208  loss_mask_4: 0.2063  loss_dice_4: 2.74  loss_bbox_4: 0.9101  loss_giou_4: 1.971  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6345  loss_mask_5: 0.2104  loss_dice_5: 2.716  loss_bbox_5: 0.9172  loss_giou_5: 1.962  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6113  loss_mask_6: 0.2045  loss_dice_6: 2.708  loss_bbox_6: 0.9004  loss_giou_6: 1.971  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6068  loss_mask_7: 0.2094  loss_dice_7: 2.643  loss_bbox_7: 0.8987  loss_giou_7: 1.969  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.6013  loss_mask_8: 0.2131  loss_dice_8: 2.598  loss_bbox_8: 0.9074  loss_giou_8: 1.961  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.6932  loss_mask_interm: 0.1718  loss_dice_interm: 3.013  loss_bbox_interm: 0.5544  loss_giou_interm: 1.778    time: 1.1859  last_time: 1.0663  data_time: 0.0164  last_data_time: 0.0115   lr: 8.1e-06  max_mem: 10363M
[08/19 22:16:42 d2.utils.events]:  eta: 9:20:25  iter: 30179  total_loss: 80.96  loss_ce: 0.619  loss_mask: 0.2128  loss_dice: 2.791  loss_bbox: 0.8845  loss_giou: 2.259  loss_ce_dn: 0  loss_mask_dn: 0  loss_dice_dn: 0  loss_bbox_dn: 0  loss_giou_dn: 0  loss_ce_0: 0.9298  loss_mask_0: 0.2463  loss_dice_0: 2.914  loss_bbox_0: 1.096  loss_giou_0: 2.245  loss_ce_dn_0: 0  loss_mask_dn_0: 0  loss_dice_dn_0: 0  loss_bbox_dn_0: 0  loss_giou_dn_0: 0  loss_ce_1: 0.8602  loss_mask_1: 0.2618  loss_dice_1: 2.878  loss_bbox_1: 0.9741  loss_giou_1: 2.255  loss_ce_dn_1: 0  loss_mask_dn_1: 0  loss_dice_dn_1: 0  loss_bbox_dn_1: 0  loss_giou_dn_1: 0  loss_ce_2: 0.7551  loss_mask_2: 0.241  loss_dice_2: 2.922  loss_bbox_2: 0.9459  loss_giou_2: 2.284  loss_ce_dn_2: 0  loss_mask_dn_2: 0  loss_dice_dn_2: 0  loss_bbox_dn_2: 0  loss_giou_dn_2: 0  loss_ce_3: 0.6825  loss_mask_3: 0.2535  loss_dice_3: 2.854  loss_bbox_3: 0.9044  loss_giou_3: 2.27  loss_ce_dn_3: 0  loss_mask_dn_3: 0  loss_dice_dn_3: 0  loss_bbox_dn_3: 0  loss_giou_dn_3: 0  loss_ce_4: 0.6389  loss_mask_4: 0.2381  loss_dice_4: 2.824  loss_bbox_4: 0.8941  loss_giou_4: 2.267  loss_ce_dn_4: 0  loss_mask_dn_4: 0  loss_dice_dn_4: 0  loss_bbox_dn_4: 0  loss_giou_dn_4: 0  loss_ce_5: 0.6276  loss_mask_5: 0.2395  loss_dice_5: 2.863  loss_bbox_5: 0.8895  loss_giou_5: 2.264  loss_ce_dn_5: 0  loss_mask_dn_5: 0  loss_dice_dn_5: 0  loss_bbox_dn_5: 0  loss_giou_dn_5: 0  loss_ce_6: 0.6134  loss_mask_6: 0.2311  loss_dice_6: 2.8  loss_bbox_6: 0.8888  loss_giou_6: 2.267  loss_ce_dn_6: 0  loss_mask_dn_6: 0  loss_dice_dn_6: 0  loss_bbox_dn_6: 0  loss_giou_dn_6: 0  loss_ce_7: 0.6356  loss_mask_7: 0.2259  loss_dice_7: 2.79  loss_bbox_7: 0.8865  loss_giou_7: 2.265  loss_ce_dn_7: 0  loss_mask_dn_7: 0  loss_dice_dn_7: 0  loss_bbox_dn_7: 0  loss_giou_dn_7: 0  loss_ce_8: 0.6221  loss_mask_8: 0.2185  loss_dice_8: 2.832  loss_bbox_8: 0.8767  loss_giou_8: 2.256  loss_ce_dn_8: 0  loss_mask_dn_8: 0  loss_dice_dn_8: 0  loss_bbox_dn_8: 0  loss_giou_dn_8: 0  loss_ce_interm: 0.9005  loss_mask_interm: 0.196  loss_dice_interm: 2.877  loss_bbox_interm: 0.6513  loss_giou_interm: 1.794    time: 1.1828  last_time: 1.0780  data_time: 0.0114  last_data_time: 0.0104   lr: 8.1e-06  max_mem: 10363M

In [ ]:
!cp /kaggle/working/SwinDocSegmenter/model_final_publay_swindocseg.pth /kaggle/working/

In [ ]:
import os

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:512"

In [ ]:
import torch
torch.cuda.empty_cache()

In [ ]:
import gc
torch.cuda.empty_cache()
gc.collect()

In [ ]:
import json
import os
from PIL import Image

# Paths
json_file_path = '/kaggle/input/banlad2599-bangla-newspaper-layout-dataset/merged_coco.json'
images_folder_path = '/kaggle/input/banlad2599-bangla-newspaper-layout-dataset/All_Crumpled_Images'
new_json_file_path = 'updated_coco.json'

# Load the existing COCO JSON file
with open(json_file_path, 'r') as file:
    coco_data = json.load(file)

# Create a mapping of image filenames to their sizes
image_size_map = {}
for image_info in coco_data['images']:
    image_file_name = image_info['file_name']
    image_path = os.path.join(images_folder_path, image_file_name)
    if os.path.exists(image_path):
        with Image.open(image_path) as img:
            width, height = img.size
            image_size_map[image_file_name] = (width, height)

# Update the COCO JSON data with the correct sizes
for image_info in coco_data['images']:
    image_file_name = image_info['file_name']
    if image_file_name in image_size_map:
        width, height = image_size_map[image_file_name]
        image_info['width'] = width
        image_info['height'] = height

# Save the updated COCO JSON data to a new file
with open(new_json_file_path, 'w') as file:
    json.dump(coco_data, file, indent=4)

print(f"Updated COCO JSON file saved to {new_json_file_path}")